---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: circleci-config-validate
        name: CircleCI config validation
        description: Test if the CircleCI config is well formed.
        entry: hooks/circleci-config-validate.sh
        language: script
        files: ^.circleci/config.yml$

